name: ⏰ Renovate

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '00 00,06,12,18 * * *'

env:
  TZ: Asia/Tokyo

permissions: write-all
jobs:
  renovate:
    name: Renovate を実行する
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: コードをチェックアウトする
        uses: actions/checkout@v4.1.7
      - uses: pnpm/action-setup@v2
        with:
          version: 9.0.4
      - name: Node.js のセットアップを行う
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: pnpm
      - name: Node のパッケージをインストールする
        run: |
          pnpm install
      - name: Renovate を実行する
        uses: renovatebot/github-action@v40.1.12
        with:
          configurationFile: renovate.json
          token: ${{ secrets.MY_PAT }}
